# Extracts a list of frames from a video.
# This was a discarded idea intended to archive a frame that was skipped from another capture
# Generated with AI after a couple turns of debugging

param (
    [string]$GoodAudio = "goodaudio.avi",
    [string]$FramesList = "frames.txt",
    [string]$OutputDir = "Extracted_Frames",
    [string]$FilterScript = "select_filter.txt"
)

# Ensure the output directory exists
if (-not (Test-Path -Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

# Grab the base filename (e.g., "goodaudio" from "goodaudio.avi")
$BaseName = [System.IO.Path]::GetFileNameWithoutExtension($GoodAudio)

# Read the frames, ensure they are numbers, and sort them sequentially
$drops = Get-Content $FramesList | Where-Object { $_ -match '^\d+$' } | ForEach-Object { [int]$_ } | Sort-Object

if ($drops.Count -eq 0) {
    Write-Host "No valid frame numbers found in $FramesList. Exiting."
    exit
}

Write-Host "Found $($drops.Count) frames to extract. Building filter..."

$offset = 0
$mappings = foreach ($d in $drops) {
    [PSCustomObject]@{
        Broken = $d
        Good   = $d + $offset
    }
    $offset++
}

# Build the FFmpeg select expression using the 'Good' indices
$selectExpr = ($mappings.Good | ForEach-Object { "eq(n,$_)" }) -join "+"

# Write to a filter script file
"select='$selectExpr'" | Out-File -FilePath $FilterScript -Encoding ASCII -Force

Write-Host "Executing FFmpeg to extract frames (Single Pass)..." -ForegroundColor Cyan

# THE EXTRACTION COMMAND
# -vsync 0 (or -fps_mode passthrough in newer builds) ensures it ONLY outputs the exact frames we selected.
$ffmpegCmd = "ffmpeg -hide_banner -y -i `"$GoodAudio`" -filter_script:v `"$FilterScript`" -fps_mode passthrough `"$OutputDir\seq_%05d.png`""

Write-Host $ffmpegCmd
Invoke-Expression $ffmpegCmd

# Verify FFmpeg didn't crash before moving on
if ($LASTEXITCODE -ne 0) {
    Write-Host "FFmpeg encountered an error during extraction. Check the console output above." -ForegroundColor Red
    exit
}

Write-Host "Extraction complete. Renaming sequence files to match absolute frame numbers..." -ForegroundColor Cyan

$i = 1
foreach ($map in $mappings) {
    # Match the 5-digit padded number generated by FFmpeg (%05d)
    $tempFile = Join-Path $OutputDir "seq_$("{0:D5}" -f $i).png"
    
    # New filename format: [VideoName]-[Brokenframenumber]-[Goodframenumber].png
    $newName = "${BaseName}-$($map.Broken)-$($map.Good).png"
    $finalPath = Join-Path $OutputDir $newName

    if (Test-Path $tempFile) {
        if (Test-Path $finalPath) { Remove-Item $finalPath -Force }
        Rename-Item -Path $tempFile -NewName $newName
    }
    $i++
}

Write-Host "Done! Lossless PNGs have been saved to the '$OutputDir' folder." -ForegroundColor Green